services:
  - docker

before_install:
  - bin/setup.sh

script: bin/test.sh

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push paulredmond/psysh:7.4
